sudo: required
language: rust
rust:
  - nightly

services:
  - docker

before_install:
  - docker build --tag sg .

script:
  - docker run -ti -v ${PWD}:/code -v ${PWD}/tmp/cargo:/root/.cargo/ sg cargo test
